[package]
name = "synth"
version = "0.2.0"
authors = ["Stephan Lagerwaard <stephanlagerwaard@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cpal = "0.15.3"
midir = "0.10.0"
wmidi = "4.0.10"
